# Generated by Django 5.0.1 on 2024-01-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_book_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='users_id',
        ),
    ]
